// Supabase Configuration
export const SUPABASE_URL = 'https://jvbuwigpqhcmwpfxgspq.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2YnV3aWdwcWhjbXdwZnhnc3BxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA1MjEwODgsImV4cCI6MTg4ODI4NzA4OH0.aMHT5VzqcPaWiswY84NeI7dQMrQY-FNf88sxgL8fVN0';
